<?php

namespace App;

use App\Saving;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Customer extends Model
{
    use SoftDeletes;
    protected $table = 'customers';
    protected $fillable = ['name', 'noKtp', 'gender', 'alamat', 'password',
        'idPegawai', 'kodeCollector', 'ppNomor', 'kodeTabungan'];
    public $incrementing = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Customer $item) {
            $countDataonTable = DB::table('customers')->orderBy('created_at', 'desc')->first();
            $code = $countDataonTable->idNasabah + 1;
            $item->idNasabah = $code;
        });

    }

}
