<?php

namespace App;

use App\Http\Middleware\Authenticate;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Employee extends Model
{
    protected $fillable = ['idPegawai','name','isAdmin','password', 'gender', 'kodeCollector'];
    public $incrementing = false;
    protected $table = 'employees';
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Employee $item){
            $code = 'A';
            $countDataonTable = Employee::count();
            $code .= str_pad($countDataonTable, 4, 0, STR_PAD_LEFT );
            $check = Employee::where('idPegawai', '=', $code)->first();
            if ($check!=null){
                $getId = Employee::orderBy('created_at', 'desc')->first();
                $getNumber = substr($getId->idPegawai, 1);
                //dd($getNumber);
                $code = "A". str_pad($getNumber +1, 4, 0, STR_PAD_LEFT );
            }
            $item->idPegawai = $code;
        });
    }
}
