<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = ['name','isUser','password', 'gender', 'kodeCollector'];
    public $incrementing = false;
    protected $table = 'employees';
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Employee $item){
            $code = 'A';
            $countDataonTable = Employee::count();
            $code .= str_pad($countDataonTable, 4, 0, STR_PAD_LEFT );
            $item->idPegawai = $code;
        });
    }
}
